### ISSUE TITLE
Mikrotik Telegram error

### ISSUE THREAD

**Issue by ashwingorityala** [Druvis-Timma/Mikrotik#3]
hai, the code is very helpful, but im receiving a error message “ expected command name (line 1 column 1” how do I rectify this

![3E359F0E-C14B-4F8C-AF12-1F4541B1B435](https://user-images.githubusercontent.com/123797059/215250911-dffc0389-82b7-42c9-a761-6336502fae48.jpeg)

**Comment by jiimint** [comment]
Hi
The command is with lower case letters:
`interface print`
You wrote the first letter of command with upper case"I" its wrong.
