### ISSUE TITLE
Failure:

### ISSUE THREAD

**Issue by Kamauink** [Druvis-Timma/Mikrotik#6]
ID: 79001067
"message_id":16,"from":{"id":xxxxxxxx,"is_bot":false,"first_name":"xxxxxxx","language_code":"en"},"chat":{"id":xxxxxxx,"first_name":"xxxxxxxx","type":"private"},"date":1676944134,"text":"System resource print"
Received: System resource print
      status: finished
  downloaded: 0KiBC-z pause]
        data: {"ok":true,"result":{"message_id":17,"from":{"id":xxxxxxxxx,"is_bot":true,"first_name":"xxxxxxx","username":"xxxxxxxxx"},"chat":{"id":xxxxxxxxx,"first_name":"xxxxxxx","type":"private"},
              "date":1676944138,"text":"Received: System resource print"}}

failure: authentication failure

**Comment by Kamauink** [comment]
I get the above error whenever I send a request from my telegram account. What could be the problem and what is the potential solution?

**Comment by Druvis-Timma** [comment]
You need to either set up an RSA certificate or simply upgrade to the latest version of RouterOS and use the ':execute <command> as-string" function in place of ssh-exec. The telegram_with_encoding.rsc has the :execute command alternative.
