### ISSUE TITLE
Question about command execution

### ISSUE THREAD

**Issue by nonPointer** [Druvis-Timma/Mikrotik#7]
https://github.com/Druvis-Timma/Mikrotik/blob/b673f20650996d135e31e209f2dced690e75b4c0/Telegram%20RouterOS/telegram_chat.rsc#L51

Why use `/system/ssh-exec` to execute the user-defined command, rather than putting them in a bracket directly? 
Many thanks!

**Comment by Druvis-Timma** [comment]
It was a workaround to copy the command output as simple text, RouterOS has been updated since then, you can use the :execute command instead.

**Comment by nonPointer** [comment]
Thanks for your explanation!
